// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFESG7jn79nhIoTVfOyp_fX1KlWGueN9M',
    appId: '1:720236276661:web:43a43660efd5c5d37cc7fc',
    messagingSenderId: '720236276661',
    projectId: 'buddy-e29dc',
    authDomain: 'buddy-e29dc.firebaseapp.com',
    storageBucket: 'buddy-e29dc.appspot.com',
    measurementId: 'G-M0TB8XHDBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp0Mredh5KEyCvtz91eUbeM3SB2o3Avg8',
    appId: '1:720236276661:android:98d3e541835033857cc7fc',
    messagingSenderId: '720236276661',
    projectId: 'buddy-e29dc',
    storageBucket: 'buddy-e29dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp5-dV42gC3JwVEVQo7lvUVOsXaCiEK5c',
    appId: '1:720236276661:ios:b86b84c35ead14377cc7fc',
    messagingSenderId: '720236276661',
    projectId: 'buddy-e29dc',
    storageBucket: 'buddy-e29dc.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp5-dV42gC3JwVEVQo7lvUVOsXaCiEK5c',
    appId: '1:720236276661:ios:b86b84c35ead14377cc7fc',
    messagingSenderId: '720236276661',
    projectId: 'buddy-e29dc',
    storageBucket: 'buddy-e29dc.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFESG7jn79nhIoTVfOyp_fX1KlWGueN9M',
    appId: '1:720236276661:web:4e2f81edaf531f337cc7fc',
    messagingSenderId: '720236276661',
    projectId: 'buddy-e29dc',
    authDomain: 'buddy-e29dc.firebaseapp.com',
    storageBucket: 'buddy-e29dc.appspot.com',
    measurementId: 'G-VDNKECWE66',
  );
}
